### ISSUE TITLE
Abnormal display on PowerShell

### ISSUE THREAD

**Issue by mistgc** [rose-pine/starship#10]
There is a issue with the display on PowerShell.
![image](https://github.com/user-attachments/assets/090f54f1-2711-46a3-9cbe-a80faed56694)

I found that fixing this problem only required a single line of code change。

```diff
diff --git a/rose-pine-dawn.toml b/rose-pine-dawn.toml
index 85b680d..e1b5608 100644
--- a/rose-pine-dawn.toml
+++ b/rose-pine-dawn.toml
@@ -18,7 +18,7 @@ $scala \
 $conda \
 $python \
 $time\n  \
-[<U+F17AA>](fg:iris)
+[<U+F17AA>](fg:iris)\
 """
```
![image](https://github.com/user-attachments/assets/b84909cc-682f-4ca1-908b-1d470d66a806)

**Comment by mistgc** [comment]
Is `git_status` disabled intentionally?

**Comment by JTrenerry** [comment]
I forgot to enable it lol

**Comment by mistgc** [comment]
Haha, I do too, occasionally.
