### ISSUE TITLE
would be great to have more modules themed

### ISSUE THREAD

**Issue by BearDad** [rose-pine/starship#4]
modules like git metrics, the language modules and such would be pretty usefull

**Comment by JTrenerry** [comment]
Can definitely do that!

**Comment by JTrenerry** [comment]
Git metrics i.e. status are there, but won't add support for languages as I personally don't use them, there is too many to configure for everyone, and its extremely easy to do so when needed (just copy the left and right borders and put whatever language you want in between them)

**Comment by BearDad** [comment]
> Git metrics i.e. status are there, but won't add support for languages as I personally don't use them, there is too many to configure for everyone, and its extremely easy to do so when needed (just copy the left and right borders and put whatever language you want in between them)

i feel you... saw the commit history you tried to make it easy for everyone and the thing went bazinga

on the note of making it easier to modify the theme and its modules it would be interesting to change the custom format from:

`format = "$username $directory $git_branch$fill $time\n  [󱞪](fg:iris) "`

to:

```
format = """
$username \
$directory \
$git_branch \
$fill \
$time\n \
[󱞪](fg:iris) 
"""

```

This way it would be waaay easier to add submodules to the promt format since you would only need to type something like '$python \ ' before or after $fill whether you want it to be left or right 
(would need to also add something like: 
```

[python]
style = "bg:overlay fg:pine"
format = "[](fg:overlay)[$symbol$version]($style)[](fg:overlay) "
disabled = false
symbol = '👾 '
```
to be able to have a cohesive submodule with the theme 
note:
with the above python submodule you can pretty much implement any langueage module since they work in the same way(you would only need to remove the symbol = ' ' line to have default icons)
like so:

![Sin título](https://github.com/user-attachments/assets/33603c07-ef33-40aa-82f4-355331f67e72)

)

**Comment by JTrenerry** [comment]
Okay, definitely agree with the first point and the languages don't look that bad when on the other side so I'll get around to that today.

Thank you!

**Comment by JTrenerry** [comment]
Ended up trying to do the most popular ones i.e. the ones I recognize at least.

They just need to be added in at the top, thank you for the suggestions!

**Comment by BearDad** [comment]
> Ended up trying to do the most popular ones i.e. the ones I recognize at least.
> 
> They just need to be added in at the top, thank you for the suggestions!

Looks good 👌 . Will try it out when I get home later today.
