### ISSUE TITLE
Typo (:wq) in rose-pine-dawn.toml

### ISSUE THREAD

**Issue by slh-git** [rose-pine/starship#5]
### Small Typo in rose-pine-dawn.toml where someone accidentally pushed :wq command right before $time
`
format = """
$username \
$directory \
$git_branch \
$git_status \
$fill \
$c \
$elixir \
$elm \
$golang \
$haskell \
$java \
$julia \
$nodejs \
$nim \
$rust \
$scala \
$python\n  \
:wq$time\n  \
[󱞪](fg:iris)
"""
`

**Comment by JTrenerry** [comment]
Oops :sweat_smile: fixed in #6 thank you!
